project:
  type: website

website:
  title: "Open Science"
  navbar:
    logo: SLUBI_logo.png
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/amrei-bp/Illustrations_for_publication
          - text: Homepage
            url:  https://amrei-bp.github.io/Illustrations_for_publication/
    left:
      - href: version_control.qmd
        text: Version Control
      - href: git_github.qmd
        text: Git and Github
      - href: git_and_r.qmd
        text: Git in Rstudio
      - href: quarto.qmd
        text: Literate Programming
      - href: tagging.qmd
        text: Tagging
      - href: patchwork.qmd
        text: Advanced plots in R

format: 
  html:
    code-fold: true
    code-summary: "Click here to show the code"
    code-tools: true
    theme: 
      - cosmo
      - test.scss
    self-contained: true
    page-layout: full
    toc: true
    toc-depth: 3
    css: styles.css
# engine: knitr

execute:
  freeze: auto




